


services:

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./provisioning:/etc/grafana/provisioning


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090

  alertmanager:
    image: prom/alertmanager:v0.27.0
    restart: unless-stopped
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - 9093:9093
    depends_on:
      prometheus:
        condition: service_started

  alertmanager-logger:
    image: alertmanager-webhook-logger
    restart: unless-stopped
    ports:
      - 6725:6725
    depends_on:
      prometheus:
        condition: service_started 

  mysqld-exporter:
    image: bitnami/mysqld-exporter
    command:
    #  - "--collect.global_variables" 
    #  - "--collect.engine_innodb_status"
    #  - "--collect.info_schema.innodb_cmp"
    #  - "--collect.info_schema.innodb_metrics"
    #  - "--collect.info_schema.innodb_cmpmem"
     - "--collect.info_schema.tables.databases=*"
    #  - "--collect.info_schema.processlist"
    #  - "--collect.slave_hosts"
    #  - "--collect.info_schema.clientstats"
    #  - "--collect.auto_increment.columns"
    #  - "--collect.binlog_size"
    #  - "--collect.global_status"
    #  - "--collect.info_schema.innodb_tablespaces"
     - "--collect.info_schema.query_response_time"
    #  - "--collect.info_schema.tables"
    #  - "--collect.info_schema.tablestats"
    #  - "--collect.info_schema.schemastats"
    #  - "--collect.info_schema.userstats"
     - "--collect.mysql.user"
    #  - "--collect.perf_schema.eventsstatements"
    #  - "--collect.perf_schema.eventswaits"
    #  - "--collect.perf_schema.file_events"
    #  - "--collect.perf_schema.file_instances"
    #  - "--collect.perf_schema.indexiowaits"
    #  - "--collect.perf_schema.tableiowaits"
    #  - "--collect.perf_schema.tablelocks"
     - "--mysqld.username=monitor:xxxx"
     - "--mysqld.address=host.docker.internal:3306"
     - "--exporter.lock_wait_timeout=10"
    container_name: mysqld-exporter

    ports:
      - 9104:9104

volumes:
  grafana_storage: {}
  prometheus_data: {}