global:
  scrape_interval: 10s
alerting:
  alertmanagers:
   - static_configs:
     - targets:
        - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mysql1'
    static_configs:
      - targets: ['host.docker.internal:9104']

  - job_name: 'mysql2'
    static_configs:
      - targets: ['host.docker.internal:9105']

  - job_name: 'mysql3'
    static_configs:
      - targets: ['host.docker.internal:9106']